server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    multiplications:
      path: /multiplications/**
      serviceId: multiplication
      strip-prefix: false
    results:
      path: /results/**
      serviceId: multiplication
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
      strip-prefix: false

# springboot2 可视化管理 http://localhost:9001/actuator
management:
  #actuator端口
  server:
    port: 9001
  #修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
  endpoints:
    #    default:
    #      web:
    #        enabled: true
    web:
      base-path: /actuator
      #开放所有页面节点  默认只开启了health、info两个节点
      exposure:
        include: "*"
    #显示健康具体信息  默认不会显示详细信息
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
